/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAccountRouteImport } from './routes/_authenticated/app.account'
import { Route as AuthenticatedAppCheckoutRouteImport } from './routes/_authenticated/app.checkout'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app.notifications'
import { Route as AuthenticatedAppPlansRouteImport } from './routes/_authenticated/app.plans'
import { Route as AuthenticatedPartnerIndexRouteImport } from './routes/_authenticated/partner.index'
import { Route as AuthenticatedAppBookCategoryRouteImport } from './routes/_authenticated/app.book.$category'
import { Route as AuthenticatedAppBookingsIndexRouteImport } from './routes/_authenticated/app.bookings.index'
import { Route as AuthenticatedAppBookingsIdRouteImport } from './routes/_authenticated/app.bookings.$id'
import { Route as ApiPublicCronRecurringRouteImport } from './routes/api/public/cron/recurring'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAccountRoute = AuthenticatedAppAccountRouteImport.update({
  id: '/app/account',
  path: '/app/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppCheckoutRoute =
  AuthenticatedAppCheckoutRouteImport.update({
    id: '/app/checkout',
    path: '/app/checkout',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/app/notifications',
    path: '/app/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppPlansRoute = AuthenticatedAppPlansRouteImport.update({
  id: '/app/plans',
  path: '/app/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartnerIndexRoute =
  AuthenticatedPartnerIndexRouteImport.update({
    id: '/partner/',
    path: '/partner/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppBookCategoryRoute =
  AuthenticatedAppBookCategoryRouteImport.update({
    id: '/app/book/$category',
    path: '/app/book/$category',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppBookingsIndexRoute =
  AuthenticatedAppBookingsIndexRouteImport.update({
    id: '/app/bookings/',
    path: '/app/bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppBookingsIdRoute =
  AuthenticatedAppBookingsIdRouteImport.update({
    id: '/app/bookings/$id',
    path: '/app/bookings/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCronRecurringRoute = ApiPublicCronRecurringRouteImport.update({
  id: '/api/public/cron/recurring',
  path: '/api/public/cron/recurring',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/checkout': typeof AuthenticatedAppCheckoutRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/plans': typeof AuthenticatedAppPlansRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/partner/': typeof AuthenticatedPartnerIndexRoute
  '/app/book/$category': typeof AuthenticatedAppBookCategoryRoute
  '/app/bookings/$id': typeof AuthenticatedAppBookingsIdRoute
  '/api/public/cron/recurring': typeof ApiPublicCronRecurringRoute
  '/app/bookings/': typeof AuthenticatedAppBookingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/checkout': typeof AuthenticatedAppCheckoutRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/plans': typeof AuthenticatedAppPlansRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/partner': typeof AuthenticatedPartnerIndexRoute
  '/app/book/$category': typeof AuthenticatedAppBookCategoryRoute
  '/app/bookings/$id': typeof AuthenticatedAppBookingsIdRoute
  '/api/public/cron/recurring': typeof ApiPublicCronRecurringRoute
  '/app/bookings': typeof AuthenticatedAppBookingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/app/account': typeof AuthenticatedAppAccountRoute
  '/_authenticated/app/checkout': typeof AuthenticatedAppCheckoutRoute
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/app/plans': typeof AuthenticatedAppPlansRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/partner/': typeof AuthenticatedPartnerIndexRoute
  '/_authenticated/app/book/$category': typeof AuthenticatedAppBookCategoryRoute
  '/_authenticated/app/bookings/$id': typeof AuthenticatedAppBookingsIdRoute
  '/api/public/cron/recurring': typeof ApiPublicCronRecurringRoute
  '/_authenticated/app/bookings/': typeof AuthenticatedAppBookingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/contact'
    | '/privacy'
    | '/refunds'
    | '/setup'
    | '/terms'
    | '/app/account'
    | '/app/checkout'
    | '/app/notifications'
    | '/app/plans'
    | '/admin/'
    | '/app/'
    | '/partner/'
    | '/app/book/$category'
    | '/app/bookings/$id'
    | '/api/public/cron/recurring'
    | '/app/bookings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/contact'
    | '/privacy'
    | '/refunds'
    | '/setup'
    | '/terms'
    | '/app/account'
    | '/app/checkout'
    | '/app/notifications'
    | '/app/plans'
    | '/admin'
    | '/app'
    | '/partner'
    | '/app/book/$category'
    | '/app/bookings/$id'
    | '/api/public/cron/recurring'
    | '/app/bookings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-login'
    | '/contact'
    | '/privacy'
    | '/refunds'
    | '/setup'
    | '/terms'
    | '/_authenticated/app/account'
    | '/_authenticated/app/checkout'
    | '/_authenticated/app/notifications'
    | '/_authenticated/app/plans'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/partner/'
    | '/_authenticated/app/book/$category'
    | '/_authenticated/app/bookings/$id'
    | '/api/public/cron/recurring'
    | '/_authenticated/app/bookings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  SetupRoute: typeof SetupRoute
  TermsRoute: typeof TermsRoute
  ApiPublicCronRecurringRoute: typeof ApiPublicCronRecurringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/account': {
      id: '/_authenticated/app/account'
      path: '/app/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AuthenticatedAppAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/checkout': {
      id: '/_authenticated/app/checkout'
      path: '/app/checkout'
      fullPath: '/app/checkout'
      preLoaderRoute: typeof AuthenticatedAppCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/app/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/plans': {
      id: '/_authenticated/app/plans'
      path: '/app/plans'
      fullPath: '/app/plans'
      preLoaderRoute: typeof AuthenticatedAppPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partner/': {
      id: '/_authenticated/partner/'
      path: '/partner'
      fullPath: '/partner/'
      preLoaderRoute: typeof AuthenticatedPartnerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/book/$category': {
      id: '/_authenticated/app/book/$category'
      path: '/app/book/$category'
      fullPath: '/app/book/$category'
      preLoaderRoute: typeof AuthenticatedAppBookCategoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/bookings/': {
      id: '/_authenticated/app/bookings/'
      path: '/app/bookings'
      fullPath: '/app/bookings/'
      preLoaderRoute: typeof AuthenticatedAppBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/bookings/$id': {
      id: '/_authenticated/app/bookings/$id'
      path: '/app/bookings/$id'
      fullPath: '/app/bookings/$id'
      preLoaderRoute: typeof AuthenticatedAppBookingsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/recurring': {
      id: '/api/public/cron/recurring'
      path: '/api/public/cron/recurring'
      fullPath: '/api/public/cron/recurring'
      preLoaderRoute: typeof ApiPublicCronRecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAccountRoute: typeof AuthenticatedAppAccountRoute
  AuthenticatedAppCheckoutRoute: typeof AuthenticatedAppCheckoutRoute
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppPlansRoute: typeof AuthenticatedAppPlansRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedPartnerIndexRoute: typeof AuthenticatedPartnerIndexRoute
  AuthenticatedAppBookCategoryRoute: typeof AuthenticatedAppBookCategoryRoute
  AuthenticatedAppBookingsIdRoute: typeof AuthenticatedAppBookingsIdRoute
  AuthenticatedAppBookingsIndexRoute: typeof AuthenticatedAppBookingsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAccountRoute: AuthenticatedAppAccountRoute,
  AuthenticatedAppCheckoutRoute: AuthenticatedAppCheckoutRoute,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppPlansRoute: AuthenticatedAppPlansRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedPartnerIndexRoute: AuthenticatedPartnerIndexRoute,
  AuthenticatedAppBookCategoryRoute: AuthenticatedAppBookCategoryRoute,
  AuthenticatedAppBookingsIdRoute: AuthenticatedAppBookingsIdRoute,
  AuthenticatedAppBookingsIndexRoute: AuthenticatedAppBookingsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  SetupRoute: SetupRoute,
  TermsRoute: TermsRoute,
  ApiPublicCronRecurringRoute: ApiPublicCronRecurringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
