/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAccountRouteImport } from './routes/_authenticated/app.account'
import { Route as AuthenticatedAppCheckoutRouteImport } from './routes/_authenticated/app.checkout'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app.notifications'
import { Route as AuthenticatedPartnerIndexRouteImport } from './routes/_authenticated/partner.index'
import { Route as AuthenticatedAppBookCategoryRouteImport } from './routes/_authenticated/app.book.$category'
import { Route as AuthenticatedAppBookingsIndexRouteImport } from './routes/_authenticated/app.bookings.index'
import { Route as AuthenticatedAppBookingsIdRouteImport } from './routes/_authenticated/app.bookings.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAccountRoute = AuthenticatedAppAccountRouteImport.update({
  id: '/app/account',
  path: '/app/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppCheckoutRoute =
  AuthenticatedAppCheckoutRouteImport.update({
    id: '/app/checkout',
    path: '/app/checkout',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/app/notifications',
    path: '/app/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartnerIndexRoute =
  AuthenticatedPartnerIndexRouteImport.update({
    id: '/partner/',
    path: '/partner/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppBookCategoryRoute =
  AuthenticatedAppBookCategoryRouteImport.update({
    id: '/app/book/$category',
    path: '/app/book/$category',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppBookingsIndexRoute =
  AuthenticatedAppBookingsIndexRouteImport.update({
    id: '/app/bookings/',
    path: '/app/bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppBookingsIdRoute =
  AuthenticatedAppBookingsIdRouteImport.update({
    id: '/app/bookings/$id',
    path: '/app/bookings/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/checkout': typeof AuthenticatedAppCheckoutRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/partner/': typeof AuthenticatedPartnerIndexRoute
  '/app/book/$category': typeof AuthenticatedAppBookCategoryRoute
  '/app/bookings/$id': typeof AuthenticatedAppBookingsIdRoute
  '/app/bookings/': typeof AuthenticatedAppBookingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/checkout': typeof AuthenticatedAppCheckoutRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/partner': typeof AuthenticatedPartnerIndexRoute
  '/app/book/$category': typeof AuthenticatedAppBookCategoryRoute
  '/app/bookings/$id': typeof AuthenticatedAppBookingsIdRoute
  '/app/bookings': typeof AuthenticatedAppBookingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/setup': typeof SetupRoute
  '/_authenticated/app/account': typeof AuthenticatedAppAccountRoute
  '/_authenticated/app/checkout': typeof AuthenticatedAppCheckoutRoute
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/partner/': typeof AuthenticatedPartnerIndexRoute
  '/_authenticated/app/book/$category': typeof AuthenticatedAppBookCategoryRoute
  '/_authenticated/app/bookings/$id': typeof AuthenticatedAppBookingsIdRoute
  '/_authenticated/app/bookings/': typeof AuthenticatedAppBookingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/app/account'
    | '/app/checkout'
    | '/app/notifications'
    | '/admin/'
    | '/app/'
    | '/partner/'
    | '/app/book/$category'
    | '/app/bookings/$id'
    | '/app/bookings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setup'
    | '/app/account'
    | '/app/checkout'
    | '/app/notifications'
    | '/admin'
    | '/app'
    | '/partner'
    | '/app/book/$category'
    | '/app/bookings/$id'
    | '/app/bookings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/setup'
    | '/_authenticated/app/account'
    | '/_authenticated/app/checkout'
    | '/_authenticated/app/notifications'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/partner/'
    | '/_authenticated/app/book/$category'
    | '/_authenticated/app/bookings/$id'
    | '/_authenticated/app/bookings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/account': {
      id: '/_authenticated/app/account'
      path: '/app/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AuthenticatedAppAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/checkout': {
      id: '/_authenticated/app/checkout'
      path: '/app/checkout'
      fullPath: '/app/checkout'
      preLoaderRoute: typeof AuthenticatedAppCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/app/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partner/': {
      id: '/_authenticated/partner/'
      path: '/partner'
      fullPath: '/partner/'
      preLoaderRoute: typeof AuthenticatedPartnerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/book/$category': {
      id: '/_authenticated/app/book/$category'
      path: '/app/book/$category'
      fullPath: '/app/book/$category'
      preLoaderRoute: typeof AuthenticatedAppBookCategoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/bookings/': {
      id: '/_authenticated/app/bookings/'
      path: '/app/bookings'
      fullPath: '/app/bookings/'
      preLoaderRoute: typeof AuthenticatedAppBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/bookings/$id': {
      id: '/_authenticated/app/bookings/$id'
      path: '/app/bookings/$id'
      fullPath: '/app/bookings/$id'
      preLoaderRoute: typeof AuthenticatedAppBookingsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAccountRoute: typeof AuthenticatedAppAccountRoute
  AuthenticatedAppCheckoutRoute: typeof AuthenticatedAppCheckoutRoute
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedPartnerIndexRoute: typeof AuthenticatedPartnerIndexRoute
  AuthenticatedAppBookCategoryRoute: typeof AuthenticatedAppBookCategoryRoute
  AuthenticatedAppBookingsIdRoute: typeof AuthenticatedAppBookingsIdRoute
  AuthenticatedAppBookingsIndexRoute: typeof AuthenticatedAppBookingsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAccountRoute: AuthenticatedAppAccountRoute,
  AuthenticatedAppCheckoutRoute: AuthenticatedAppCheckoutRoute,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedPartnerIndexRoute: AuthenticatedPartnerIndexRoute,
  AuthenticatedAppBookCategoryRoute: AuthenticatedAppBookCategoryRoute,
  AuthenticatedAppBookingsIdRoute: AuthenticatedAppBookingsIdRoute,
  AuthenticatedAppBookingsIndexRoute: AuthenticatedAppBookingsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
